// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b9642fb8ac07f7164dc643ddd1fa99b58ae9be8b/react/react-dom.d.ts
declare namespace __ReactV {
    import React = __React;
    class Grid extends React.Component<any, any> {
    }
    class AutoSizer extends React.Component<any, any> {
    }
    class ScrollSync extends React.Component<any, any> {
    }

}

declare module "react-virtualized" {
    import DOM = __ReactV;
    export = DOM;
}

